 package com.example.revdev.data

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.withContext
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import java.io.IOException
import kotlinx.coroutines.CancellationException
import okhttp3.Call
import okhttp3.Callback
import okhttp3.Response
import java.io.BufferedReader
import java.io.InputStreamReader
import java.util.concurrent.TimeUnit
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonArray

object OpenAIApi {
    private const val API_URL = "https://openrouter.ai/api/v1/chat/completions" // OpenRouter endpoint
    private const val API_KEY = "" // OpenRouter API key
    private val client = OkHttpClient.Builder()
        .readTimeout(0, TimeUnit.MILLISECONDS) // Disable read timeout for streaming
        .build()
    private val json = Json { ignoreUnknownKeys = true }
    
    // Rate limiting variables
    private var lastRequestTime = 0L
    private val minRequestInterval = 1000L // 1 second between requests

    suspend fun ask(question: String): String {
        return withContext(Dispatchers.IO) {
            try {
                // Rate limiting: ensure minimum time between requests
                val currentTime = System.currentTimeMillis()
                val timeSinceLastRequest = currentTime - lastRequestTime
                if (timeSinceLastRequest < minRequestInterval) {
                    delay(minRequestInterval - timeSinceLastRequest)
                }
                lastRequestTime = System.currentTimeMillis()
                
                val requestBody = json.encodeToString(
                    OpenAIRequest.serializer(),
                    OpenAIRequest(
                        model = "google/gemma-3n-e2b-it:free",
                        messages = listOf(OpenAIMessage(role = "user", content = question)),
                        maxTokens = 256
                    )
                ).toRequestBody("application/json".toMediaType())

                val request = Request.Builder()
                    .url(API_URL)
                    .addHeader("Authorization", "Bearer $API_KEY")
                    .addHeader("Content-Type", "application/json")
                    .post(requestBody)
                    .build()

                client.newCall(request).execute().use { response ->
                    when (response.code) {
                        200 -> {
                            val body = response.body?.string() ?: return@withContext "No response body"
                            val completion = json.decodeFromString(OpenAIResponse.serializer(), body)
                            return@withContext completion.choices.firstOrNull()?.message?.content?.trim() ?: "No answer"
                        }
                        429 -> {
                            // Rate limit exceeded - wait and retry once
                            delay(2000) // Wait 2 seconds
                            return@withContext "Rate limit exceeded. Please wait a moment and try again."
                        }
                        401 -> {
                            return@withContext "Authentication error. Please check your API key."
                        }
                        403 -> {
                            return@withContext "Access forbidden. Please check your API key permissions."
                        }
                        500, 502, 503, 504 -> {
                            return@withContext "Server error. Please try again later."
                        }
                        else -> {
                            return@withContext "Error ${response.code}: ${response.message}"
                        }
                    }
                }
            } catch (e: IOException) {
                return@withContext "Network error: ${e.message}"
            } catch (e: Exception) {
                return@withContext "Error: ${e.message}"
            }
        }
    }

    /**
     * Streams the answer as it is generated by the model.
     * Usage: OpenAIApi.askStream(question) { partialText -> ... }
     */
    suspend fun askStream(question: String, onToken: (String) -> Unit): String = withContext(Dispatchers.IO) {
        // Rate limiting: ensure minimum time between requests
        val currentTime = System.currentTimeMillis()
        val timeSinceLastRequest = currentTime - lastRequestTime
        if (timeSinceLastRequest < minRequestInterval) {
            delay(minRequestInterval - timeSinceLastRequest)
        }
        lastRequestTime = System.currentTimeMillis()

        val requestJson = buildString {
            append("{" )
            append("\"model\":\"google/gemma-3n-e2b-it:free\",")
            append("\"messages\":[{\"role\":\"user\",\"content\":\"${question.replace("\"", "\\\"")}\"}],")
            append("\"max_tokens\":256,")
            append("\"stream\":true")
            append("}")
        }
        val requestBody = requestJson.toRequestBody("application/json".toMediaType())
        val request = Request.Builder()
            .url(API_URL)
            .addHeader("Authorization", "Bearer $API_KEY")
            .addHeader("Content-Type", "application/json")
            .post(requestBody)
            .build()
        try {
            client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    return@withContext when (response.code) {
                        429 -> "Rate limit exceeded. Please wait a moment and try again."
                        401 -> "Authentication error. Please check your API key."
                        403 -> "Access forbidden. Please check your API key permissions."
                        500, 502, 503, 504 -> "Server error. Please try again later."
                        else -> "Error ${response.code}: ${response.message}"
                    }
                }
                val reader = BufferedReader(InputStreamReader(response.body?.byteStream()))
                val answer = StringBuilder()
                var line: String?
                while (reader.readLine().also { line = it } != null) {
                    if (line.isNullOrBlank() || !line!!.startsWith("data:")) continue
                    val jsonLine = line!!.removePrefix("data:").trim()
                    if (jsonLine == "[DONE]") break
                    try {
                        val event = kotlinx.serialization.json.Json.parseToJsonElement(jsonLine)
                        val content = event.jsonObject["choices"]
                            ?.jsonArray?.getOrNull(0)?.jsonObject
                            ?.get("delta")?.jsonObject?.get("content")?.toString()?.trim('"')
                        if (!content.isNullOrEmpty()) {
                            answer.append(content)
                            onToken(answer.toString())
                        }
                    } catch (_: Exception) { /* ignore parse errors for partial lines */ }
                }
                return@withContext answer.toString().ifBlank { "No answer" }
            }
        } catch (e: IOException) {
            return@withContext "Network error: ${e.message}"
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            return@withContext "Error: ${e.message}"
        }
    }
}

@Serializable
data class OpenAIRequest(
    val model: String,
    val messages: List<OpenAIMessage>,
    @SerialName("max_tokens") val maxTokens: Int = 256
)

@Serializable
data class OpenAIMessage(
    val role: String,
    val content: String
)

@Serializable
data class OpenAIResponse(
    val choices: List<OpenAIChoice>
)

@Serializable
data class OpenAIChoice(
    val message: OpenAIMessage
)